### ISSUE TITLE
Compile failed: Node 7.2.1   6.9.2   6.3.1   4.6.2   4.4.7   liblzma.a: No such file or directory. /bin/sh: 1: ./node_modules/.bin/coffee: not found

### ISSUE THREAD

**Issue by lope** [oorabona/node-liblzma#10]
Running Ubuntu 14.04 and I have installed liblzma-dev.
Using node v7.2.1 (npm v3.10.10)
6.9.2 also failed
6.3.1 also failed

```
> node-liblzma@1.0.4-12 install /tmp/lztest/node_modules/node-liblzma
> ubs install

Installing node-liblzma version 1.0.4-12 Add-On ...
node-pre-gyp ERR! Tried to download(406): https://github.com/oorabona/node-liblzma/node-liblzma-v1.0.4-12-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-liblzma@1.0.4-12 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/tmp/lztest/node_modules/node-liblzma/build'
  CXX(target) Release/obj.target/node-liblzma/src/bindings/node-liblzma.o
../src/bindings/node-liblzma.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE LZMA::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/bindings/node-liblzma.cpp:66:83: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/bob/.node-gyp/7.2.1/include/node/v8.h:3287): Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(Nan::New<Function>(constructor)->NewInstance(0, NULL));
                                                                                   ^
  CXX(target) Release/obj.target/node-liblzma/src/bindings/module.o
  SOLINK_MODULE(target) Release/obj.target/node-liblzma.node
g++: error: /tmp/lztest/node_modules/node-liblzma/deps/xz/lib/liblzma.a: No such file or directory
make: *** [Release/obj.target/node-liblzma.node] Error 1
make: Leaving directory `/tmp/lztest/node_modules/node-liblzma/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.8j4kmem+
gyp ERR! command "/home/bob/.nvm/versions/node/v7.2.1/bin/node" "/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/lztest/node_modules/node-liblzma/build/node-liblzma.node" "--module_name=node-liblzma" "--module_path=/tmp/lztest/node_modules/node-liblzma/build"
gyp ERR! cwd /tmp/lztest/node_modules/node-liblzma
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/bob/.nvm/versions/node/v7.2.1/bin/node /home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/lztest/node_modules/node-liblzma/build/node-liblzma.node --module_name=node-liblzma --module_path=/tmp/lztest/node_modules/node-liblzma/build' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/lztest/node_modules/node-liblzma/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.8j4kmem+
node-pre-gyp ERR! command "/home/bob/.nvm/versions/node/v7.2.1/bin/node" "/tmp/lztest/node_modules/node-liblzma/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/lztest/node_modules/node-liblzma
node-pre-gyp ERR! node -v v7.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/home/bob/.nvm/versions/node/v7.2.1/bin/node /home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/lztest/node_modules/node-liblzma/build/node-liblzma.node --module_name=node-liblzma --module_path=/tmp/lztest/node_modules/node-liblzma/build' (1)
ERROR: Result 1 is *NOT* ok. Result: { ok: false, env: {} }
Build done.
```

This tool http://cryto.net/why-is-npm-broken/ said I needed to update the old packages.
So I ran `npm update` then I tried to install again.

```
$ npm i --save --verbose node-liblzma@*
> node-liblzma@1.0.4-12 install /tmp/node-liblzma-test/node_modules/node-liblzma
> ubs install

Installing node-liblzma version 1.0.4-12 Add-On ...
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/home/bob/.nvm/versions/node/v7.2.1/bin/node',
node-pre-gyp verb cli   '/tmp/node-liblzma-test/node_modules/node-liblzma/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@7.2.1 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/tmp/node-liblzma-test/node_modules/node-liblzma/build/node-liblzma.node" (not found)
node-pre-gyp http GET https://github.com/oorabona/node-liblzma/node-liblzma-v1.0.4-12-node-v51-linux-x64.tar.gz
node-pre-gyp http 406 https://github.com/oorabona/node-liblzma/node-liblzma-v1.0.4-12-node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(406): https://github.com/oorabona/node-liblzma/node-liblzma-v1.0.4-12-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-liblzma@1.0.4-12 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 406 status code downloading tarball https://github.com/oorabona/node-liblzma/node-liblzma-v1.0.4-12-node-v51-linux-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp verb cli [ '/home/bob/.nvm/versions/node/v7.2.1/bin/node',
gyp verb cli   '/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'clean' ]
gyp info using node-gyp@3.4.0
gyp info using node@7.2.1 | linux | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/home/bob/.nvm/versions/node/v7.2.1/bin/node',
gyp verb cli   '/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/tmp/node-liblzma-test/node_modules/node-liblzma/build/node-liblzma.node',
gyp verb cli   '--module_name=node-liblzma',
gyp verb cli   '--module_path=/tmp/node-liblzma-test/node_modules/node-liblzma/build' ]
gyp info using node-gyp@3.4.0
gyp info using node@7.2.1 | linux | x64
gyp verb command configure []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 7.2.1
gyp verb command install [ '7.2.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.2.1"
gyp verb install installing version: 7.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 7.2.1
gyp verb build dir attempting to create "build" dir: /tmp/node-liblzma-test/node_modules/node-liblzma/build
gyp verb build dir "build" dir needed to be created? /tmp/node-liblzma-test/node_modules/node-liblzma/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /tmp/node-liblzma-test/node_modules/node-liblzma/build/config.gypi
gyp verb config.gypi checking for gypi file: /tmp/node-liblzma-test/node_modules/node-liblzma/config.gypi
gyp verb common.gypi checking for gypi file: /tmp/node-liblzma-test/node_modules/node-liblzma/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/node-liblzma-test/node_modules/node-liblzma/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bob/.node-gyp/7.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/bob/.node-gyp/7.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/node-liblzma-test/node_modules/node-liblzma',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/home/bob/.nvm/versions/node/v7.2.1/bin/node',
gyp verb cli   '/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/tmp/node-liblzma-test/node_modules/node-liblzma/build/node-liblzma.node',
gyp verb cli   '--module_name=node-liblzma',
gyp verb cli   '--module_path=/tmp/node-liblzma-test/node_modules/node-liblzma/build' ]
gyp info using node-gyp@3.4.0
gyp info using node@7.2.1 | linux | x64
gyp verb command build []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/bob/.node-gyp/7.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/tmp/node-liblzma-test/node_modules/node-liblzma/build'
  g++ '-DNODE_GYP_MODULE_NAME=node-liblzma' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/bob/.node-gyp/7.2.1/include/node -I/home/bob/.node-gyp/7.2.1/src -I/home/bob/.node-gyp/7.2.1/deps/uv/include -I/home/bob/.node-gyp/7.2.1/deps/v8/include -I../../nan -I/tmp/node-liblzma-test/node_modules/node-liblzma/deps/xz/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/node-liblzma/src/bindings/node-liblzma.o.d.raw -fPIC  -c -o Release/obj.target/node-liblzma/src/bindings/node-liblzma.o ../src/bindings/node-liblzma.cpp
../src/bindings/node-liblzma.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE LZMA::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/bindings/node-liblzma.cpp:66:83: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/bob/.node-gyp/7.2.1/include/node/v8.h:3287): Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(Nan::New<Function>(constructor)->NewInstance(0, NULL));
                                                                                   ^
  g++ '-DNODE_GYP_MODULE_NAME=node-liblzma' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/bob/.node-gyp/7.2.1/include/node -I/home/bob/.node-gyp/7.2.1/src -I/home/bob/.node-gyp/7.2.1/deps/uv/include -I/home/bob/.node-gyp/7.2.1/deps/v8/include -I../../nan -I/tmp/node-liblzma-test/node_modules/node-liblzma/deps/xz/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/node-liblzma/src/bindings/module.o.d.raw -fPIC  -c -o Release/obj.target/node-liblzma/src/bindings/module.o ../src/bindings/module.cpp
  g++ -shared -pthread -rdynamic -m64  -Wl,-soname=node-liblzma.node -o Release/obj.target/node-liblzma.node -Wl,--start-group Release/obj.target/node-liblzma/src/bindings/node-liblzma.o Release/obj.target/node-liblzma/src/bindings/module.o -Wl,--end-group /tmp/node-liblzma-test/node_modules/node-liblzma/deps/xz/lib/liblzma.a
g++: error: /tmp/node-liblzma-test/node_modules/node-liblzma/deps/xz/lib/liblzma.a: No such file or directory
make: *** [Release/obj.target/node-liblzma.node] Error 1
make: Leaving directory `/tmp/node-liblzma-test/node_modules/node-liblzma/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.8
gyp ERR! command "/home/bob/.nvm/versions/node/v7.2.1/bin/node" "/home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/node-liblzma-test/node_modules/node-liblzma/build/node-liblzma.node" "--module_name=node-liblzma" "--module_path=/tmp/node-liblzma-test/node_modules/node-liblzma/build"
gyp ERR! cwd /tmp/node-liblzma-test/node_modules/node-liblzma
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/bob/.nvm/versions/node/v7.2.1/bin/node /home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node-liblzma-test/node_modules/node-liblzma/build/node-liblzma.node --module_name=node-liblzma --module_path=/tmp/node-liblzma-test/node_modules/node-liblzma/build' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/node-liblzma-test/node_modules/node-liblzma/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.8
node-pre-gyp ERR! command "/home/bob/.nvm/versions/node/v7.2.1/bin/node" "/tmp/node-liblzma-test/node_modules/node-liblzma/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/node-liblzma-test/node_modules/node-liblzma
node-pre-gyp ERR! node -v v7.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/home/bob/.nvm/versions/node/v7.2.1/bin/node /home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node-liblzma-test/node_modules/node-liblzma/build/node-liblzma.node --module_name=node-liblzma --module_path=/tmp/node-liblzma-test/node_modules/node-liblzma/build' (1)
ERROR: Result 1 is *NOT* ok. Result: { ok: false, env: {} }
Build done.
npm verb lifecycle node-liblzma@1.0.4-12~install: unsafe-perm in lifecycle true
npm verb lifecycle node-liblzma@1.0.4-12~install: PATH: /home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/npm/bin/node-gyp-bin:/tmp/node-liblzma-test/node_modules/node-liblzma/node_modules/.bin:/tmp/node-liblzma-test/node_modules/.bin:/home/bob/.nvm/versions/node/v7.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/android-studio/bin:/opt/android-ndk-r11c
npm verb lifecycle node-liblzma@1.0.4-12~install: CWD: /tmp/node-liblzma-test/node_modules/node-liblzma
npm info lifecycle node-liblzma@1.0.4-12~postinstall: node-liblzma@1.0.4-12
npm verb unlock done using /home/bob/.npm/_locks/staging-89b612eefe527949.lock for /tmp/node-liblzma-test/node_modules/.staging
npm verb saving [ { name: 'node-liblzma', spec: '^1.0.4-12', save: 'dependencies' } ]
- ansi@0.3.1 node_modules/ansi
- lodash.pad@4.5.1 node_modules/lodash.pad
- lodash.padend@4.6.1 node_modules/lodash.padend
- lodash.padstart@4.6.1 node_modules/lodash.padstart
- gauge@1.2.7 node_modules/node-liblzma/node_modules/gauge
- npmlog@2.0.4 node_modules/node-liblzma/node_modules/npmlog
- once@1.3.3 node_modules/node-liblzma/node_modules/once
- readable-stream@2.1.5 node_modules/node-liblzma/node_modules/readable-stream
- semver@5.1.1 node_modules/node-liblzma/node_modules/semver
- tar-pack@3.1.4 node_modules/node-liblzma/node_modules/tar-pack
- node-pre-gyp@0.6.28 node_modules/node-liblzma/node_modules/node-pre-gyp
node-liblzma-test@1.0.0 /tmp/node-liblzma-test
└── node-liblzma@1.0.4-12 

npm WARN node-liblzma-test@1.0.0 No description
npm verb 
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN node-liblzma-test@1.0.0 No repository field.
npm verb 
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb exit [ 0, true ]
npm info ok 
```

now I got this error
```
npm ERR! Linux 4.4.8
npm ERR! argv "/home/bob/.nvm/versions/node/v7.2.1/bin/node" "/home/bob/.nvm/versions/node/v7.2.1/bin/npm" "i" "--save" "node-liblzma@*"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/bob/.npm/node-liblzma/1.0.3/package.tgz archive: ENOENT: no such file or directory, open '/home/bob/.npm/node-liblzma/1.0.3/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/node-liblzma-test/npm-debug.log
```

Build on node 4.4.7 / 4.6.2 problem
```
$ npm i --save --build-from-source node-liblzma@*
npm WARN package.json node-liblzma-test@1.0.0 No description
npm WARN package.json node-liblzma-test@1.0.0 No repository field.
npm WARN package.json node-liblzma-test@1.0.0 No README data
-
> node-liblzma@1.0.4 install /tmp/node-liblzma-test/node_modules/node-liblzma
> ubs install

Building node-liblzma version 1.0.4 Add-On ...
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/tmp/node-liblzma-test/node_modules/node-liblzma/build'
  CXX(target) Release/obj.target/node-liblzma/src/bindings/node-liblzma.o
  CXX(target) Release/obj.target/node-liblzma/src/bindings/module.o
  SOLINK_MODULE(target) Release/obj.target/node-liblzma.node
  COPY Release/node-liblzma.node
  COPY /tmp/node-liblzma-test/node_modules/node-liblzma/build/node-liblzma.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/tmp/node-liblzma-test/node_modules/node-liblzma/build'
Building Javascript API...
/bin/sh: 1: ./node_modules/.bin/coffee: not found
Done building Javascript.
Build done.
npm WARN unmet dependency /tmp/node-liblzma-test/node_modules/node-liblzma/node_modules/node-pre-gyp requires npmlog@'~2.0.0' but will load
npm WARN unmet dependency /tmp/node-liblzma-test/node_modules/npmlog,
npm WARN unmet dependency which is version 4.0.2
npm WARN unmet dependency /tmp/node-liblzma-test/node_modules/node-liblzma/node_modules/node-pre-gyp requires semver@'~5.1.0' but will load
npm WARN unmet dependency /tmp/node-liblzma-test/node_modules/semver,
npm WARN unmet dependency which is version 5.3.0
npm WARN unmet dependency /tmp/node-liblzma-test/node_modules/node-liblzma/node_modules/node-pre-gyp requires tar-pack@'~3.1.0' but will load
npm WARN unmet dependency /tmp/node-liblzma-test/node_modules/tar-pack,
npm WARN unmet dependency which is version 3.3.0
node-liblzma@1.0.4 node_modules/node-liblzma
```

joepie on #node.js freenode said:
`<joepie91> Lope: right. that's a bug in the package; they should be publishing JS rather than coffeescript (and if they *do* insist on compiling on install time, coffeescript should be a dependency and not a devDependency like it is now)`

**Comment by joeyhub** [comment]
I also fund that out and fixed it in my pull request (my master is ahead of that pull request though as I'm adding raw encoding).

**Comment by oorabona** [comment]
Hi back 5 years later !
I eventually found some time to migrate everything and make it work all the way thru.
This therefore should no longer be an issue.

@joeyhub Coffee tends to keep things cleaner than even ES6/7 but that's very opinionated I agree.
Eventually all boils down to Javascript.

Probably some time soon I will add types too.
