### ISSUE TITLE
Can't require node-liblzma

### ISSUE THREAD

**Issue by lope** [oorabona/node-liblzma#9]
Attempted with: (same error)
Node v7.2.1 (npm v3.10.10)
Node v6.9.2 (npm v3.10.9)

Installed: "node-liblzma": "^1.0.4-12"

I tried requiring as recommended by the readme.md
```
var lzma = require('lzma');

Error: Cannot find module 'lzma'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/lztest/main.js:1:74)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
joshua@dev-mach /tmp/lztest $ node main.js
module.js:472
    throw err;
    ^
```

I tried requiring by the actual module name.
```
var lzma = require('node-liblzma');

Error: Cannot find module '../build/Release/node-liblzma.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/lztest/node_modules/node-liblzma/lib/lzma.js:26:13)
    at Object.<anonymous> (/tmp/lztest/node_modules/node-liblzma/lib/lzma.js:381:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

Confirmed by 2 other people
```
<fnordbart> Lope: fwiw, installing node-liblzma fails here, too. "g++: error: /tmp/t/node_modules/node-liblzma/deps/xz/lib/liblzma.a: No such file or directory"

<doodadjs> Lope: with "node-liblzma", I have the same error then you. I could try node 6.9.2
<Lope> doodadjs: I tried node 6.9.2. it didn't work.
```

http://cryto.net/why-is-npm-broken/
says I'm missing the `lzma.h` module.
I seem to have misread the instructions. I thought I only needed to compile for multithread support.

I scrolled up the install now and I see it actually had an error compiling. I just missed it because there's soooo many dependencies and the bottom of the install log looks okay.

Since installing liblzma-dev it's gone further.

**Comment by lope** [comment]
I'm reopening this because I don't know much about making npm modules, but I think the build process should be improved if possible. This package uses a zillion dependencies. After the compile fails, the MASSIVE list of dependencies is displayed after installation and the installation appaers to have succeeded unless you scroll up to look for errors.
It would be better if errors cause the installation to stop.

Problems installing:
https://github.com/oorabona/node-liblzma/issues/10
